### ISSUE TITLE
QGLContext::chooseMacVisual: Unable to choose a pixel format

### ISSUE THREAD

**Issue by Jermmy** [zddhub/trianglemesh#4]
Hello zddhub, I run your program and get an error.
This is the command I run `./gen_view_image ../../data/teddy.off ../../data/view/ 102 teddy_images/`
And I get the output like this: 
```
Reading ../../data/teddy.off...
  Reading 12543 vertices...
  Reading 25082 faces... Done.
Find adjacent faces...Done.
Finding across-edge maps... Done.
Building triangle strips...Done.
 3010 strips (Avg. length 8.3)
Computing bounding sphere... Done.
  center = (-0.103948, 0.0948819, 0.143286), radius = 0.911894
Computing normals... Done.
Computing point areas... Done.
Computing curvatures... Done.
Computing dcurv... Done.
compute curvatures: 0.015000
QGLContext::chooseMacVisual: Unable to choose a pixel format
QGLContext::chooseMacVisual: Unable to choose a pixel format
...
```
Could you give me some tips to fix it?

**Comment by Jermmy** [comment]
Device is Macbook Pro(Intel Iris Graphics). OS is macOS Sierra. Qt version 4.8.7

**Comment by zddhub** [comment]
It seams like Qt4.6~4.8 issue. Which Qt version do you use? I used Qt 5.6 and everything is ok.

**Comment by Jermmy** [comment]
Well, I update to Qt5.8 and it works. Thanks for your help!
