### ISSUE TITLE
Could not find qmake configuration file macx-clang

### ISSUE THREAD

**Issue by leopeng1995** [zddhub/trianglemesh#6]
I cloned this project and executed this command:
```
$ qmake ../trianglemesh.pro -o Makefile
```

And then got this error:

```
Could not find qmake configuration file macx-clang.
Error processing project file: ../trianglemesh.pro
```

I thought the reason is qt version. But I reverted it to qt4, and got the same error. My system is OSX 10.12.6. Thx.

**Comment by zddhub** [comment]
Try this version:

QT:
 ```sh
$ qmake --version
QMake version 3.0
Using Qt version 5.6.2 in $HOME/Tools/Qt5.6.2/5.6/clang_64/lib
```
Mac: Version 10.13 (17A405)

**Comment by leopeng1995** [comment]
Thx! The key point is $HOME/Tools/Qt5.6.2/5.6/clang_64/lib. Actually, my qmake was Anaconda version by default before. I changed it to Homebrew version and then solved it.
