### ISSUE TITLE
Error reading file

### ISSUE THREAD

**Issue by 3aptiste3** [zddhub/trianglemesh#9]
Hi,
First thx for your work !
I succeeded to build trianglemesh on Ubuntu, but when I want to apply gen_view_image on teddy.off, I have this error :
"
Reading 12543 vertices... Error reading file [~/data/teddy.off].
read file ~/data/teddy.off error.
"
Is there something I do wrong ?
Thank you,
Baptiste

**Comment by 3aptiste3** [comment]
In trianglemesh_io.cpp :
`if (!ok || mesh->vertices.empty()) {
            eprintf("Error reading file [%s].\n", filename);
            return false;`
But I don't don't understand why ?

**Comment by 3aptiste3** [comment]
Hello,
I found the problem, I added "-fopenmp -lm -pthread" to CFLAGS, CXXFLAGS and LFLAGS in the Makefile. It works now.
![makefile_trianglemesh](https://user-images.githubusercontent.com/40884795/45632234-1cc36780-ba9d-11e8-8b69-4ce2e6e8bdb2.png)

Baptiste

**Comment by zddhub** [comment]
Great work @3aptiste3 , 👍 .
